#!python
import distutils.sysconfig, os.path

package_dir = os.path.join(distutils.sysconfig.get_python_lib(0,0), 's2')

env = Environment(
   SWIGFLAGS=['-python', '-c++'],
   SWIGPATH=['../s2'],
   CPPPATH=[distutils.sysconfig.get_python_inc(), '..', '../s2'],
   LIBS=['s2', 's2cellid'],
   LIBPATH='..',
   SHLIBPREFIX='',
)

lib_s2 = env.LoadableModule('_s2', ['s2.i'])

env.Install(package_dir, [lib_s2, 's2.py', '__init__.py'])
env.Alias('install', package_dir)

